---
#arun
- hosts: machine1
  vars:
    - var1: variable1
    - var2: variable2
  tasks:
    - name: task1
      block:
        - shell: echo '{{ var1 }}' > /home/ansible/variable.txt
        - file: path='/home/ansible/{{ var1 }}.txt' state=touch
